var Parser = require('../lib/parser/hiredis').Parser;
var assert = require('assert');

/*
This test makes sure that exceptions thrown inside of "reply" event handlers
are not trapped and mistakenly emitted as parse errors.
*/
(function testExecuteDoesNotCatchReplyCallbackExceptions() {
  var parser = new Parser();
  var replies = [{***REMOVED***];

  parser.reader = {
    feed: function() {***REMOVED***,
    get: function() {
      return replies.shift();
    ***REMOVED***
  ***REMOVED***;

  var emittedError = false;
  var caughtException = false;

  parser
    .on('error', function() {
      emittedError = true;
    ***REMOVED***)
    .on('reply', function() {
      throw new Error('bad');
    ***REMOVED***);

  try {
    parser.execute();
  ***REMOVED*** catch (err) {
    caughtException = true;
  ***REMOVED***

  assert.equal(caughtException, true);
  assert.equal(emittedError, false);
***REMOVED***)();
