
/**
 * Module dependencies.
 */

var assert = require('assert')
var Promise = require('../lib/promise');

/**
 * Test.
 */

describe('promise', function(){
  it('events fire right after fulfill()', function(done){
    var promise = new Promise()
      , called = 0;

    promise.on('fulfill', function (a, b) {
      assert.equal(a, '1');
      assert.equal(b, '2');
      called++;
    ***REMOVED***);

    promise.fulfill('1', '2');

    promise.on('fulfill', function (a, b) {
      assert.equal(a, '1');
      assert.equal(b, '2');
      called++;
    ***REMOVED***);

    assert.equal(2, called);
    done();
  ***REMOVED***);

  it('events fire right after reject()', function(done){
    var promise = new Promise()
      , called = 0;

    promise.on('reject', function (err) {
      assert.ok(err instanceof Error);
      called++;
    ***REMOVED***);

    promise.reject(new Error('booyah'));

    promise.on('reject', function (err) {
      assert.ok(err instanceof Error);
      called++;
    ***REMOVED***);

    assert.equal(2, called);
    done()
  ***REMOVED***);

  describe('onResolve()', function(){
    it('from constructor works', function(done){
      var called = 0;

      var promise = new Promise(function (err) {
        assert.ok(err instanceof Error);
        called++;
      ***REMOVED***)

      promise.reject(new Error('dawg'));

      assert.equal(1, called);
      done();
    ***REMOVED***);

    it('after fulfill()', function(done){
      var promise = new Promise()
        , called = 0;

      promise.fulfill('woot');

      promise.onResolve(function (err, data){
        assert.equal(data,'woot');
        called++;
      ***REMOVED***);

      promise.onResolve(function (err, data){
        assert.strictEqual(err, null);
        called++;
      ***REMOVED***);

      assert.equal(2, called);
      done();
    ***REMOVED***)
  ***REMOVED***);

  describe('onFulfill shortcut', function(){
    it('works', function(done){
      var promise = new Promise()
        , called = 0;

      promise.onFulfill(function (woot) {
        assert.strictEqual(woot, undefined);
        called++;
      ***REMOVED***);

      promise.fulfill();

      assert.equal(1, called);
      done();
    ***REMOVED***)
  ***REMOVED***)

  describe('onReject shortcut', function(){
    it('works', function(done){
      var promise = new Promise()
        , called = 0;

      promise.onReject(function (err) {
        assert.ok(err instanceof Error);
        called++;
      ***REMOVED***);

      promise.reject(new Error);
      assert.equal(1, called);
      done();
    ***REMOVED***)
  ***REMOVED***);

  describe('return values', function(){
    it('on()', function(done){
      var promise = new Promise()
      assert.ok(promise.on('jump', function(){***REMOVED***) instanceof Promise);
      done()
    ***REMOVED***);

    it('onFulfill()', function(done){
      var promise = new Promise()
      assert.ok(promise.onFulfill(function(){***REMOVED***) instanceof Promise);
      done();
    ***REMOVED***)
    it('onReject()', function(done){
      var promise = new Promise()
      assert.ok(promise.onReject(function(){***REMOVED***) instanceof Promise);
      done();
    ***REMOVED***)
    it('onResolve()', function(done){
      var promise = new Promise()
      assert.ok(promise.onResolve(function(){***REMOVED***) instanceof Promise);
      done();
    ***REMOVED***)
  ***REMOVED***)

  describe('casting errors', function(){
    describe('reject()', function(){
      it('does not cast arguments to Error', function(done){
        var p = new Promise(function (err, arg) {
          assert.equal(3, err);
          done();
        ***REMOVED***);

        p.reject(3);
      ***REMOVED***)
    ***REMOVED***)
  ***REMOVED***)

  describe('then catching', function(){
    it('should not catch returned promise fulfillments', function(done){
      var p1 = new Promise;

      var p2 = p1.then(function () { return 'step 1' ***REMOVED***)

      p2.onFulfill(function () { throw new Error('fulfill threw me') ***REMOVED***)
      p2.reject = assert.ifError.bind(assert, new Error('reject should not have been called'));

      setTimeout(function () {
        assert.throws(function () {
          p1.fulfill();
        ***REMOVED***, /fulfill threw me/)
        done();
      ***REMOVED***, 10);

    ***REMOVED***)

    it('can be disabled using .end()', function(done){
      var p = new Promise;

      var p2 = p.then(function () { throw new Error('shucks') ***REMOVED***)
      p2.end();

      setTimeout(function () {
        try {
          p.fulfill();
        ***REMOVED*** catch (err) {
          assert.ok(/shucks/.test(err))
          done();
        ***REMOVED***

        setTimeout(function () {
          done(new Error('error was swallowed'));
        ***REMOVED***, 10);

      ***REMOVED***, 10);
    ***REMOVED***)
  ***REMOVED***)
***REMOVED***)
